server:
  port: 8079  #其实就是 http://localhost:8080/eureka/


spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        instanceId:   registry1
        health-check-interval: 10s
        health-check-url: http://localhost:8079/health
        hostname: localhost
        port: ${server.port}
        tags: dev
        service-name: registry
