
spring:
  cloud:
    consul:
          host: localhost
          port: 8500
          enabled: true
          discovery:
            instanceId:   gateway1
            health-check-interval: 10s
            health-check-url: http://localhost:8079/health
            hostname: localhost
            port: ${server.port}
            tags: dev
            service-name: gateway
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    service0: /service/0/**
    service1: /service/1/**
    #这里的配置表示，访问/baidu/** 直接重定向到http://www.baidu.com
    baidu:
      path: /baidu/**
      url: http://www.baidu.com

